[build]
command = "npm install --omit=dev"

[deploy]
startCommand = "node bot.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[[services]]
name = "bot"
sourceDir = "/"

[[services]]
name = "postgres"
sourceDir = "/"
